fprintf ("The splitting of test and validation data was done in train_svm. By separating the pos and neg features\n" + ...
    "through splicing.\n");

fprintf ("The training set had an accuracy of 99.1 after the training. When using the weights and bias against\n" + ...
    "the validation set, the resulting accuracy was 98.6. In an attempt to improve the accuracy, the hog cellsize\n" + ...
    "was decreased. As a result, the number of features increased from 1161 to 2511. Afterwards, the lambda value was\n" + ...
    "increased. This yielded poorer results, as such, the lambda value was decreased. This improved the accuracy of\n" + ...
    "the training set to 99.9 and the validation set to 99.7. The lambda value was decreased from 0.1 to 0.001\n");


